"""Mini Caribou — WSL HPC Benchmark Manager (STREAM / HPL / HPCG)."""
import os, sys, json, argparse, subprocess, time, shutil
from collections import defaultdict

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)

from compiler import preprocess_compiler, preprocess_compiler_forced, detect_compiler, COMPILERS
from slurm    import preprocess_slurm, wait_and_show
import hpc_apps.stream as stream_app
import hpc_apps.hpl    as hpl_app
import hpc_apps.hpcg   as hpcg_app


# ─── System Info ──────────────────────────────────────────────────────────────

def get_system_info():
    cores = int(subprocess.run(["nproc"], capture_output=True, text=True).stdout.strip())
    host  = subprocess.run(["hostname"], capture_output=True, text=True).stdout.strip()
    mem_mb, avail_mb = 4096, 1024          # defaults if /proc/meminfo is unavailable
    try:
        # FIX 1: use 'with' so file handle is always closed
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemTotal"):     mem_mb   = int(line.split()[1]) // 1024
                if line.startswith("MemAvailable"): avail_mb = int(line.split()[1]) // 1024
    except OSError:
        pass
    return {"cores": cores, "host": host, "mem_mb": mem_mb, "avail_mb": avail_mb}


# ─── Lmod Module ──────────────────────────────────────────────────────────────

def write_lmod_module(app, compiler_name, ci, workspace):
    mod_dir   = os.path.join(workspace, "modules", app, compiler_name)
    os.makedirs(mod_dir, exist_ok=True)
    build_dir = os.path.join(workspace, app, "build")
    run_dir   = os.path.join(workspace, app, "run")
    A, C = app.upper(), compiler_name.upper()
    with open(os.path.join(mod_dir, "1.0.lua"), "w") as f:
        f.write(f"""\
-- Auto-generated by Mini Caribou
whatis("Name: {A}  Compiler: {C}  CC: {ci['cc']}  Flags: {ci['flags']}")
help([[{A} built with {C}. Build: {build_dir}  Run: {run_dir}]])
prepend_path("PATH", "{build_dir}")
prepend_path("PATH", "{run_dir}")
setenv("CARIBOU_{A}_BUILD", "{build_dir}")
setenv("CARIBOU_{A}_RUN",   "{run_dir}")
setenv("CARIBOU_COMPILER",  "{C}")
setenv("CARIBOU_CC",        "{ci['cc']}")
""")
    print(f"     Lmod: module use {os.path.join(workspace, 'modules')}"
          f"  &&  module load {app}/{compiler_name}/1.0")


# ─── Log Directories ──────────────────────────────────────────────────────────

def make_job_logdir(workspace, app, job_type="run"):
    # Timestamped folder so logs from different runs never overwrite each other
    log_dir = os.path.join(workspace, app, "logs",
                           f"case_{time.strftime('%Y%m%d_%H%M%S')}_{job_type}_{app}")
    os.makedirs(log_dir, exist_ok=True)
    b = os.path.join(log_dir, app)
    return log_dir, f"{b}.out", f"{b}.err", f"{b}.sbatch", os.path.join(log_dir, "case_setup.json")


def write_case_setup(path, app, job_type, compiler_name, ci, threads, np, iteration, sysinfo):
    with open(path, "w") as f:
        json.dump({"app": app, "job_type": job_type, "compiler": compiler_name,
                   "cc": ci["cc"], "flags": ci["flags"], "threads": threads,
                   "np": np, "iteration": iteration,
                   "host": sysinfo.get("host"), "cores": sysinfo.get("cores"),
                   "mem_mb": sysinfo.get("mem_mb"), "avail_mb": sysinfo.get("avail_mb"),
                   "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S")}, f, indent=2)


# ─── Job Success Detection ────────────────────────────────────────────────────

SUCCESS_MARKERS = {
    "stream": ["Triad:", "Results saved to"],
    "hpl":    ["WR", "HPL_result", "Results saved to"],
    "hpcg":   ["HPCG_result"],
    "build":  ["Binary OK", "Done :"],
}
FAIL_MARKERS = ["ERROR:", "error:", "compile failed", "xhpl not found",
                "exit 1", "No such file or directory", "Segmentation fault", "command not found"]


def check_log(log_path, app, job_type):
    if not log_path or not os.path.exists(log_path):
        return False, "log not found"
    # FIX 2: 'with' block + line-by-line scan — avoids loading entire file into memory
    # and stops at the first hit instead of scanning everything
    key      = "build" if job_type == "build" else app
    markers  = SUCCESS_MARKERS.get(key, ["Done :"])
    found_ok = None
    with open(log_path) as f:
        for line in f:
            for m in FAIL_MARKERS:
                if m in line: return False, f"fail: '{m}'"
            if found_ok is None:
                for m in markers:
                    if m in line: found_ok = f"ok: '{m}'"
    if found_ok:
        return True, found_ok
    return False, "empty" if not os.path.getsize(log_path) else "no success marker"


def check_slurm_job(job_id):
    try:
        r = subprocess.run(
            ["sacct", "-j", str(job_id), "--format=JobID,State,ExitCode", "--noheader", "-P"],
            capture_output=True, text=True, timeout=10)
        if r.returncode != 0 or not r.stdout.strip():
            return None, "sacct empty"
        parts = r.stdout.strip().splitlines()[0].split("|")
        state, ec = parts[1].strip().upper(), (parts[2].strip() if len(parts) > 2 else "?")
        if state in ("COMPLETED", "COMPLETING"):         return True,  f"state={state} exit={ec}"
        if state in ("FAILED", "CANCELLED", "TIMEOUT"):  return False, f"state={state} exit={ec}"
        return None, f"state={state}"   # still running or unknown
    except FileNotFoundError: return None, "sacct not found"
    except Exception as e:    return None, str(e)


def job_succeeded(job_id, out_log, app="stream", job_type="run"):
    if job_id == "skip": return True
    # Non-SLURM paths (direct bash) — just scan the log
    if job_id in ("bash", None) or str(job_id).startswith("direct_"):
        return check_log(out_log, app, job_type)[0]
    # SLURM path — trust scheduler state first, then verify via log
    slurm_ok, _ = check_slurm_job(job_id)
    if slurm_ok is True:  return check_log(out_log, app, job_type)[0]
    if slurm_ok is False: return False
    return check_log(out_log, app, job_type)[0]  # sacct inconclusive → fall back to log


# ─── Metric Extractors ────────────────────────────────────────────────────────

def extract_gflops_hpl(log_path):
    # HPL result line: "WR <N> <NB> <P> <Q> <time> <Gflops>"  → index 6
    if not log_path or not os.path.exists(log_path): return None
    with open(log_path) as f:                        # FIX 3: 'with' for safe file handling
        for line in f:
            if line.strip().startswith("WR"):
                parts = line.split()
                if len(parts) >= 7:
                    try: return float(parts[6])
                    except ValueError: pass
    return None


def extract_gflops_hpcg(log_path):
    # HPCG result line: "HPCG_result : iters=N  residual=X  GFlops=Y"
    if not log_path or not os.path.exists(log_path): return None
    with open(log_path) as f:                        # FIX 3: 'with' for safe file handling
        for line in f:
            if line.strip().startswith("HPCG_result"):
                for part in line.split():
                    if part.startswith("GFlops="):
                        try: return float(part.split("=")[1])
                        except ValueError: pass
    return None


def extract_triad(log_path):
    # STREAM result line: "Triad:  <best_rate_MB/s>  <avg_time> ..."
    if not log_path or not os.path.exists(log_path): return None
    with open(log_path) as f:                        # FIX 3: 'with' for safe file handling
        for line in f:
            if line.strip().startswith("Triad:"):
                parts = line.split()
                if len(parts) >= 2:
                    try: return float(parts[1])
                    except ValueError: pass
    return None


def print_stream_results(log_path):
    if not log_path or not os.path.exists(log_path): return
    with open(log_path) as f:                        # FIX 3: 'with' for safe file handling
        lines = f.readlines()
    seps = [i for i, l in enumerate(lines) if "-----" in l]
    if len(seps) < 2: return
    # One line above first separator = column header; last separator = end of data rows
    # This captures: Function header + Copy + Scale + Add + Triad
    start, end = max(0, seps[0] - 1), seps[-1] + 1
    print("\n  [STREAM Results]")
    for line in lines[start:end]:
        print("  " + line.rstrip())
    print()


# ─── Summary Table ────────────────────────────────────────────────────────────

def print_summary_table(results):
    if not results:
        print("\n  (no results)"); return

    # Collect metrics from run jobs only, then average per app
    buckets = defaultdict(list)
    for r in results:
        if r.get("job_type") != "run": continue
        if r["app"] in ("hpl", "hpcg") and r.get("gflops") is not None:
            buckets[r["app"]].append(r["gflops"])
        if r["app"] == "stream" and r.get("triad") is not None:
            buckets["stream"].append(r["triad"])
    avg = {a: sum(v) / len(v) for a, v in buckets.items() if v}

    apps        = {r["app"] for r in results}
    show_gflops = bool(apps & {"hpl", "hpcg"})
    show_triad  = "stream" in apps

    W = {"app": 8, "compiler": 9, "job_type": 12, "iter": 5,
         "threads": 8, "np": 4, "status": 9, "log": 30}
    if show_gflops: W["gflops"] = W["avg_gflops"] = 12
    if show_triad:  W["triad"]  = W["avg_triad"]  = 12

    def cell(v, w, right=False):
        return str(v).rjust(w) if right else str(v).ljust(w)

    def header_row():
        labels = ["App","Compiler","Job Type","Iter","Threads","NP","Status"]
        keys   = ["app","compiler","job_type","iter","threads","np","status"]
        if show_gflops: labels += ["Gflops","Avg Gflops"]; keys += ["gflops","avg_gflops"]
        if show_triad:  labels += ["Triad MB/s","Avg Triad"]; keys += ["triad","avg_triad"]
        labels += ["Log Dir"]; keys += ["log"]
        metric_keys = {"gflops","avg_gflops","triad","avg_triad"}
        return "  │ " + " │ ".join(cell(l, W[k], k in metric_keys)
                                   for l, k in zip(labels, keys)) + " │"

    def data_row(r):
        sym       = "✔" if r["status"] == "PASS" else "✗"
        short_log = os.path.basename(r.get("log_dir") or "-")
        is_run    = r.get("job_type") == "run"
        row = (f"  │ {cell(r['app'],W['app'])} │ {cell(r['compiler'],W['compiler'])} │"
               f" {cell(r['job_type'],W['job_type'])} │ {cell(r.get('iteration','-'),W['iter'])} │"
               f" {cell(r.get('threads','-'),W['threads'])} │ {cell(r.get('np','-'),W['np'])} │"
               f" {cell(sym+' '+r['status'],W['status'])}")
        if show_gflops:
            gf     = f"{r['gflops']:.4e}"   if (is_run and r["app"] in ("hpl","hpcg") and r.get("gflops") is not None) else "-"
            avg_gf = f"{avg[r['app']]:.4e}" if (is_run and r["app"] in avg) else "-"
            row   += f" │ {cell(gf,W['gflops'],True)} │ {cell(avg_gf,W['avg_gflops'],True)}"
        if show_triad:
            tr     = f"{r['triad']:.2f}"    if (is_run and r["app"] == "stream" and r.get("triad") is not None) else "-"
            avg_tr = f"{avg['stream']:.2f}" if (is_run and "stream" in avg) else "-"
            row   += f" │ {cell(tr,W['triad'],True)} │ {cell(avg_tr,W['avg_triad'],True)}"
        return row + f" │ {cell(short_log,W['log'])} │"

    # Border width calculated from column widths + separators
    w   = sum(W.values()) + 3 * len(W) + 1
    top = "  ┌" + "─" * (w - 4) + "┐"
    mid = "  ├" + "─" * (w - 4) + "┤"
    bot = "  └" + "─" * (w - 4) + "┘"

    print("\n  ╔══════════════════════════════════════╗")
    print(  "  ║   CARIBOU  —  POST-PROCESSING REPORT ║")
    print(  "  ╚══════════════════════════════════════╝\n")
    print(top); print(header_row()); print(mid)

    pass_count = fail_count = 0
    for r in results:
        print(data_row(r))
        pass_count += r["status"] == "PASS"
        fail_count += r["status"] == "FAIL"

    print(bot)
    print(f"\n  Summary: {pass_count+fail_count} jobs  │  ✔ PASS: {pass_count}  │  ✗ FAIL: {fail_count}")
    for label, key in [("HPL","hpl"), ("HPCG","hpcg")]:
        if key in avg:
            print(f"  Avg Gflops ({label})  : {avg[key]:.4e}  (over {len(buckets[key])} run(s))")
    if "stream" in avg:
        print(f"  Avg Triad MB/s    : {avg['stream']:.2f}  (over {len(buckets['stream'])} run(s))")

    failures = [r for r in results if r["status"] == "FAIL"]
    if failures:
        print("\n  ✗ FAILED JOBS:")
        for r in failures:
            print(f"    • {r['app']}/{r['job_type']}  iter={r.get('iteration','-')}"
                  f"  threads={r.get('threads','-')}  np={r.get('np','-')}  jobid={r.get('job_id','-')}")
            if r.get("log_dir"): print(f"      Log: {r['log_dir']}")
    print()


# ─── Shared Helpers ───────────────────────────────────────────────────────────

def _make_record(app, compiler, job_type, iteration, threads, np,
                 ok, log_dir, job_id, gflops=None, triad=None):
    return {"app": app, "compiler": compiler, "job_type": job_type,
            "iteration": iteration, "threads": threads, "np": np,
            "status": "PASS" if ok else "FAIL",
            "log_dir": log_dir, "job_id": job_id, "gflops": gflops, "triad": triad}


def _move_logs(src_out, src_err, dst_out, dst_err):
    for src, dst in [(src_out, dst_out), (src_err, dst_err)]:
        if os.path.exists(src): shutil.move(src, dst)


# ─── Build Stage ──────────────────────────────────────────────────────────────

def run_build(app, threads, np, iteration, workspace, compiler_name, ci, sysinfo):
    build_dir = os.path.join(workspace, app, "build")
    os.makedirs(build_dir, exist_ok=True)
    temp_out = os.path.join(build_dir, f"{app}.out")
    temp_err = os.path.join(build_dir, f"{app}.err")

    if app == "stream":
        build_jid = stream_app.build(build_dir, threads, ci, sysinfo,
                                     out_log=temp_out, err_log=temp_err, workspace=workspace)
        binary = None
    elif app == "hpl":
        build_jid, binary = hpl_app.build(build_dir, threads, ci, compiler_name,
                                           out_log=temp_out, err_log=temp_err, workspace=workspace)
    else:  # hpcg
        build_jid, binary = hpcg_app.build(build_dir, threads, ci, compiler_name,
                                            out_log=temp_out, err_log=temp_err, workspace=workspace)

    if build_jid and build_jid not in ("skip", "bash"):
        wait_and_show(build_jid, temp_out, f"build_{app}")

    log_dir, b_out, b_err, b_sbatch, b_case = make_job_logdir(workspace, app, "build")
    _move_logs(temp_out, temp_err, b_out, b_err)
    write_case_setup(b_case, app, "build", compiler_name, ci, threads, np, iteration, sysinfo)

    # Copy sbatch script into log dir so each run is fully reproducible
    sbatch_names = {"hpl": f"build_hpl_{compiler_name}.sh", "hpcg": f"build_hpcg_{compiler_name}.sh"}
    sbatch_src = os.path.join(build_dir, sbatch_names.get(app, "build_stream.sh"))
    if os.path.exists(sbatch_src): shutil.copy(sbatch_src, b_sbatch)

    print(f"  ✔  BUILD  →  {log_dir}")
    b_ok = job_succeeded(build_jid, b_out, app=app, job_type="build")
    # Skip/bash builds don't go to SLURM so don't need a result row
    record = None if build_jid in ("skip", "bash", None) else \
             _make_record(app, compiler_name, "build", iteration, threads, np,
                          b_ok, log_dir, build_jid)
    return build_jid, binary, record, b_ok


# ─── Run Stage ────────────────────────────────────────────────────────────────

def run_benchmark(app, threads, np, iteration, workspace, compiler_name, ci, sysinfo,
                  build_jid, binary):
    build_dir = os.path.join(workspace, app, "build")
    run_dir   = os.path.join(workspace, app, "run", f"iter{iteration}_t{threads}_np{np}")
    os.makedirs(run_dir, exist_ok=True)

    # Standard binary locations when not returned from build stage
    if binary is None and app == "hpl":
        binary = os.path.join(build_dir, "hpl-2.3", "bin", f"Linux_HPL_{compiler_name}", "xhpl")
    if binary is None and app == "hpcg":
        binary = os.path.join(build_dir, "xhpcg")

    temp_out = os.path.join(run_dir, f"{app}.out")
    temp_err = os.path.join(run_dir, f"{app}.err")

    if app == "stream":
        run_jid, _ = stream_app.run(build_dir, run_dir, threads, build_jid, ci,
                                    out_log=temp_out, err_log=temp_err, workspace=workspace)
    elif app == "hpl":
        run_jid, _ = hpl_app.run(build_dir, run_dir, np, threads, build_jid, binary, ci, sysinfo,
                                  out_log=temp_out, err_log=temp_err, workspace=workspace)
    else:  # hpcg
        run_jid, _ = hpcg_app.run(build_dir, run_dir, np, threads, build_jid, binary, ci, sysinfo,
                                   out_log=temp_out, err_log=temp_err, workspace=workspace)

    if run_jid and run_jid not in ("bash",):
        wait_and_show(run_jid, None, f"run_{app}")

    log_dir, final_out, final_err, r_sbatch, r_case = make_job_logdir(workspace, app, "run")
    _move_logs(temp_out, temp_err, final_out, final_err)
    write_case_setup(r_case, app, "run", compiler_name, ci, threads, np, iteration, sysinfo)

    sbatch_src = os.path.join(run_dir, f"run_{app}.sh")
    if os.path.exists(sbatch_src): shutil.copy(sbatch_src, r_sbatch)

    if app == "stream": print_stream_results(final_out)

    r_ok   = job_succeeded(run_jid, final_out, app=app, job_type="run")
    gflops = extract_gflops_hpl(final_out)  if app == "hpl"    else \
             extract_gflops_hpcg(final_out) if app == "hpcg"   else None
    triad  = extract_triad(final_out)       if app == "stream" else None

    print(f"  ✔  RUN    →  {log_dir}")
    return _make_record(app, compiler_name, "run", iteration, threads, np,
                        r_ok, log_dir, run_jid, gflops=gflops, triad=triad)


# ─── Case Runner (single iteration × threads × np) ───────────────────────────

def run_one_case(app, threads, np, iteration, action, workspace, compiler_name, ci, sysinfo):
    results   = []
    build_jid = None
    binary    = None
    # FIX 4: copy before mutating so the pipeline's shared sysinfo dict is not affected
    sysinfo   = dict(sysinfo)
    sysinfo["compiler_name"] = compiler_name

    if action in ("build", "all"):
        build_jid, binary, build_record, b_ok = run_build(
            app, threads, np, iteration, workspace, compiler_name, ci, sysinfo)
        if build_record: results.append(build_record)
        if not b_ok:
            print(f"\n  ✗  Build failed — skipping run (iter={iteration} t={threads} np={np})")
            return results

    if action in ("run", "all"):
        results.append(run_benchmark(
            app, threads, np, iteration, workspace, compiler_name, ci, sysinfo, build_jid, binary))

    return results


# ─── Pipeline (sweeps iterations × threads × np) ─────────────────────────────

def run_pipeline(app, threads_list, np_list, iterations_list, action, workspace, compiler_name, ci):
    sysinfo     = get_system_info()
    all_results = []
    write_lmod_module(app, compiler_name, ci, workspace)

    for iteration in iterations_list:
        for threads in threads_list:
            for np in np_list:
                # sysinfo copy now handled inside run_one_case (FIX 4)
                all_results.extend(run_one_case(
                    app, threads, np, iteration, action, workspace,
                    compiler_name, ci, sysinfo))

    print_summary_table(all_results)

    summary_path = os.path.join(workspace, app, "logs", "summary.json")
    os.makedirs(os.path.dirname(summary_path), exist_ok=True)
    with open(summary_path, "w") as f:
        json.dump(all_results, f, indent=2)
    print(f"  Summary JSON : {summary_path}")
    return all_results


# ─── SLURM Preprocessing ──────────────────────────────────────────────────────

def run_slurm_preprocessing():
    # FIX 5: reuse get_system_info() result instead of calling nproc again in main()
    info = get_system_info()
    print("=" * 64)
    print(f"  Host: {info['host']}  Cores: {info['cores']}"
          f"  RAM: {info['mem_mb']} MB total / {info['avail_mb']} MB avail")
    print("=" * 64)
    preprocess_slurm()
    return info  # return so main() can reuse it if needed


# ─── Argument Parsing ─────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(description="Mini Caribou — WSL HPC Benchmark Manager",
                                formatter_class=argparse.RawTextHelpFormatter)
    p.add_argument("--slurm",      choices=["preprocessing"], metavar="MODE")
    p.add_argument("--apps",       choices=["stream", "hpl", "hpcg"])
    p.add_argument("--action",     choices=["build", "run", "all"], default="all")
    p.add_argument("--threads",    type=int, nargs="+", default=[1],  metavar="T")
    p.add_argument("--np",         type=int, nargs="+", default=None, metavar="N")
    p.add_argument("--iterations", type=int, nargs="+", default=[1],  metavar="N",
                   help="--iterations 3 → runs iters 1,2,3")
    p.add_argument("--compiler",   choices=["gcc", "aocc", "icc"], default=None)
    p.add_argument("--skip-preprocess", action="store_true")
    return p.parse_args()


# ─── Entry Point ──────────────────────────────────────────────────────────────

def main():
    args    = parse_args()
    # FIX 5: call get_system_info() once here; reuse result everywhere in main()
    sysinfo = get_system_info()

    if args.slurm == "preprocessing":
        print("=" * 64)
        print(f"  Host: {sysinfo['host']}  Cores: {sysinfo['cores']}"
              f"  RAM: {sysinfo['mem_mb']} MB total / {sysinfo['avail_mb']} MB avail")
        print("=" * 64)
        preprocess_slurm()
        return

    if not args.apps:
        print("  ✗  --apps <stream|hpl|hpcg>  or  --slurm preprocessing  is required.")
        sys.exit(1)

    workspace  = os.path.join(BASE_DIR, "workspace")
    np_list    = args.np or [sysinfo["cores"]]   # FIX 5: reuse cores from sysinfo, no second nproc call
    # Single value N → expand to [1..N]; multiple values → use as-is
    iters_list = list(range(1, args.iterations[0] + 1)) if len(args.iterations) == 1 else args.iterations

    print("=" * 64)
    print(f"  App: {args.apps.upper()}  Action: {args.action}  "
          f"Threads: {args.threads}  NP: {np_list}  Iters: {iters_list}")
    print(f"  Workspace: {workspace}")
    print("=" * 64)

    # Compiler: forced via --compiler flag, or auto-detected
    if args.compiler:
        compiler_name, ci = args.compiler, COMPILERS[args.compiler]
        if not args.skip_preprocess: preprocess_compiler_forced(compiler_name, ci)
    else:
        if not args.skip_preprocess:
            compiler_name, ci = preprocess_compiler()
        else:
            compiler_name, ci = detect_compiler()

    print(f"  ✔  Compiler : {compiler_name.upper()}  ({ci['cc']})")
    os.makedirs(workspace, exist_ok=True)

    run_pipeline(app=args.apps, threads_list=args.threads, np_list=np_list,
                 iterations_list=iters_list, action=args.action,
                 workspace=workspace, compiler_name=compiler_name, ci=ci)


if __name__ == "__main__":
    main()
