"""
Mini Caribou — WSL HPC Benchmark Manager
Auto-detects compiler, manages builds, Lmod module generation,
structured per-job logs, post-processing summary table.
"""
import os
import sys
import json
import argparse
import subprocess
import time
import shutil
from collections import defaultdict

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)

from compiler import preprocess_compiler, preprocess_compiler_forced, detect_compiler, COMPILERS
from slurm    import preprocess_slurm, wait_and_show, make_sbatch, write_script, sbatch_submit
import hpc_apps.stream as stream_app
import hpc_apps.hpl    as hpl_app
import hpc_apps.hpcg   as hpcg_app   # ← CHANGE 1: hpcg import
import uprof


# ─────────────────────────────────────────────────────────────
# SYSTEM INFO
# ─────────────────────────────────────────────────────────────

def get_system_info():
    cores = int(subprocess.run(
        ["nproc"], capture_output=True, text=True).stdout.strip())
    host  = subprocess.run(
        ["hostname"], capture_output=True, text=True).stdout.strip()
    mem_mb, avail_mb = 4096, 1024
    try:
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemTotal"):
                    mem_mb = int(line.split()[1]) // 1024
                if line.startswith("MemAvailable"):
                    avail_mb = int(line.split()[1]) // 1024
    except:
        pass
    return {"cores": cores, "host": host,
            "mem_mb": mem_mb, "avail_mb": avail_mb}


# ─────────────────────────────────────────────────────────────
# LMOD MODULE GENERATION
# ─────────────────────────────────────────────────────────────

def write_lmod_module(app, compiler_name, compiler_info, workspace):
    mod_dir  = os.path.join(workspace, "modules", app, compiler_name)
    os.makedirs(mod_dir, exist_ok=True)
    mod_file = os.path.join(mod_dir, "1.0.lua")

    build_dir = os.path.join(workspace, app, "build")
    run_dir   = os.path.join(workspace, app, "run")

    lua = f"""\
-- Lmod modulefile for {app.upper()} built with {compiler_name.upper()}
-- Auto-generated by Mini Caribou
whatis("Name        : {app.upper()}")
whatis("Version     : 1.0")
whatis("Compiler    : {compiler_name.upper()}")
whatis("CC          : {compiler_info['cc']}")
whatis("Flags       : {compiler_info['flags']}")
whatis("Build dir   : {build_dir}")
whatis("Run dir     : {run_dir}")

help([[
  {app.upper()} benchmark built with {compiler_name.upper()}.
  Build directory : {build_dir}
  Run   directory : {run_dir}
  Load with       : module load {app}/{compiler_name}/1.0
]])

local build = "{build_dir}"
local run   = "{run_dir}"

prepend_path("PATH",         build)
prepend_path("PATH",         run)
setenv("CARIBOU_{app.upper()}_BUILD", build)
setenv("CARIBOU_{app.upper()}_RUN",   run)
setenv("CARIBOU_COMPILER",            "{compiler_name.upper()}")
setenv("CARIBOU_CC",                  "{compiler_info['cc']}")
"""
    with open(mod_file, "w") as f:
        f.write(lua)

    print(f"     Lmod module written : {mod_file}")
    print(f"     Load with : module use {os.path.join(workspace, 'modules')}")
    print(f"                 module load {app}/{compiler_name}/1.0")
    return mod_file


# ─────────────────────────────────────────────────────────────
# STRUCTURED LOG DIR  —  case_{timestamp}_{job_type}_{app}
# ─────────────────────────────────────────────────────────────

def make_job_logdir(workspace, app, job_type="run"):
    """Name: case_YYYYMMDD_HHMMSS_{job_type}_{app}"""
    ts      = time.strftime("%Y%m%d_%H%M%S")
    folder  = f"case_{ts}_{job_type}_{app}"
    log_dir = os.path.join(workspace, app, "logs", folder)
    os.makedirs(log_dir, exist_ok=True)

    out_log    = os.path.join(log_dir, f"{app}.out")
    err_log    = os.path.join(log_dir, f"{app}.err")
    sbatch_cp  = os.path.join(log_dir, f"{app}.sbatch")
    case_setup = os.path.join(log_dir, "case_setup.json")

    return log_dir, out_log, err_log, sbatch_cp, case_setup


def write_case_setup(path, app, job_type, compiler_name, compiler_info,
                     threads, np, iteration, system_info, extra=None):
    data = {
        "app":          app,
        "job_type":     job_type,
        "compiler":     compiler_name,
        "cc":           compiler_info["cc"],
        "flags":        compiler_info["flags"],
        "threads":      threads,
        "np":           np,
        "iteration":    iteration,
        "host":         system_info.get("host", "?"),
        "cores_system": system_info.get("cores", "?"),
        "mem_mb":       system_info.get("mem_mb", "?"),
        "avail_mb":     system_info.get("avail_mb", "?"),
        "timestamp":    time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    if extra:
        data.update(extra)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    return data


# ─────────────────────────────────────────────────────────────
# JOB STATUS CHECK
# ─────────────────────────────────────────────────────────────

SUCCESS_MARKERS = {
    "stream": ["Triad:", "Results saved to"],
    "hpl":    ["WR", "HPL_result", "Results saved to"],
    "hpcg":   ["HPCG_result"],
    "build":  ["Binary OK", "Done :"],
}

FAIL_MARKERS = [
    "ERROR:", "error:", "compile failed", "xhpl not found",
    "exit 1", "No such file or directory", "Segmentation fault",
    "command not found", "No such file",
]


def check_log_for_success(log_path, app, job_type):
    if not log_path or not os.path.exists(log_path):
        return False, "log file not found"
    with open(log_path) as f:
        content = f.read()
    for marker in FAIL_MARKERS:
        if marker in content:
            return False, f"fail marker: '{marker}'"
    key     = "build" if job_type == "build" else app
    markers = SUCCESS_MARKERS.get(key, ["Done :"])
    for marker in markers:
        if marker in content:
            return True, f"success marker: '{marker}'"
    if len(content.strip()) > 0:
        return False, "no success marker in log"
    return False, "log is empty"


# ─────────────────────────────────────────────────────────────
# METRIC EXTRACTORS
# ─────────────────────────────────────────────────────────────

def extract_gflops(log_path):
    """Extract Gflops from HPL output (WR... line)."""
    if not log_path or not os.path.exists(log_path):
        return None
    with open(log_path) as f:
        for line in f:
            stripped = line.strip()
            if stripped.startswith("WR"):
                parts = stripped.split()
                if len(parts) >= 7:
                    try:
                        return float(parts[6])
                    except ValueError:
                        pass
    return None


def extract_gflops_hpcg(log_path):
    """Extract Gflops from HPCG output (HPCG_result line)."""
    if not log_path or not os.path.exists(log_path):
        return None
    with open(log_path) as f:
        for line in f:
            stripped = line.strip()
            if stripped.startswith("HPCG_result"):
                # format: HPCG_result : iters=N  residual=X  GFlops=Y
                for part in stripped.split():
                    if part.startswith("GFlops="):
                        try:
                            return float(part.split("=")[1])
                        except ValueError:
                            pass
    return None


def extract_triad(log_path):
    """Extract Triad bandwidth (MB/s) from STREAM output."""
    if not log_path or not os.path.exists(log_path):
        return None
    with open(log_path) as f:
        for line in f:
            stripped = line.strip()
            if stripped.startswith("Triad:"):
                parts = stripped.split()
                if len(parts) >= 2:
                    try:
                        return float(parts[1])
                    except ValueError:
                        pass
    return None


def print_stream_results(log_path):
    """Print the STREAM bandwidth table to terminal after run completes."""
    if not log_path or not os.path.exists(log_path):
        return
    with open(log_path) as f:
        lines = f.readlines()
    sep_indices = [i for i, l in enumerate(lines) if "-----" in l]
    if len(sep_indices) < 2:
        return
    print()
    print("  [STREAM Results]")
    for line in lines[sep_indices[0]:sep_indices[1] + 1]:
        print("  " + line.rstrip())
    print()


def job_succeeded_slurm(job_id):
    try:
        r = subprocess.run(
            ["sacct", "-j", str(job_id),
             "--format=JobID,State,ExitCode",
             "--noheader", "-P"],
            capture_output=True, text=True, timeout=10)
        if r.returncode != 0 or not r.stdout.strip():
            return None, "sacct returned nothing"
        first_line = r.stdout.strip().splitlines()[0]
        parts      = first_line.split("|")
        if len(parts) >= 2:
            state    = parts[1].strip().upper()
            exitcode = parts[2].strip() if len(parts) > 2 else "?"
            if state in ("COMPLETED", "COMPLETING"):
                return True,  f"SLURM state={state} exit={exitcode}"
            elif state in ("FAILED", "CANCELLED", "TIMEOUT", "NODE_FAIL"):
                return False, f"SLURM state={state} exit={exitcode}"
            else:
                return None,  f"SLURM state={state} (inconclusive)"
    except FileNotFoundError:
        return None, "sacct not available"
    except Exception as e:
        return None, f"sacct exception: {e}"
    return None, "sacct parse failed"


def job_succeeded(job_id, out_log, app="stream", job_type="run"):
    if job_id == "skip":
        return True
    if job_id in ("bash", None) or str(job_id).startswith("direct_"):
        ok, _ = check_log_for_success(out_log, app, job_type)
        return ok
    slurm_ok, _ = job_succeeded_slurm(job_id)
    if slurm_ok is not None:
        if slurm_ok:
            log_ok, _ = check_log_for_success(out_log, app, job_type)
            if not log_ok:
                return False
        return slurm_ok
    ok, _ = check_log_for_success(out_log, app, job_type)
    return ok


# ─────────────────────────────────────────────────────────────
# POST-PROCESSING SUMMARY TABLE
# ─────────────────────────────────────────────────────────────

def print_summary_table(results):
    if not results:
        print("\n  (no results to show)")
        return

    # Per-app averages over run jobs only
    buckets = defaultdict(list)
    for r in results:
        if r.get("job_type") != "run":
            continue
        if r["app"] == "hpl"    and r.get("gflops") is not None:
            buckets["hpl"].append(r["gflops"])
        if r["app"] == "hpcg"   and r.get("gflops") is not None:
            buckets["hpcg"].append(r["gflops"])
        if r["app"] == "stream" and r.get("triad")  is not None:
            buckets["stream"].append(r["triad"])
    avg_map = {app: sum(v) / len(v) for app, v in buckets.items() if v}

    # Detect which apps are present to decide metric columns
    apps_present = {r["app"] for r in results}
    show_gflops  = bool(apps_present & {"hpl", "hpcg"})
    show_triad   = "stream" in apps_present

    W = {"app": 8, "compiler": 9, "job_type": 12,
         "iter": 5, "threads": 8, "np": 4, "status": 9, "log": 30}
    if show_gflops:
        W["gflops"]     = 12
        W["avg_gflops"] = 12
    if show_triad:
        W["triad"]      = 12
        W["avg_triad"]  = 12

    def cell(val, width, right=False):
        s = str(val)
        return s.rjust(width) if right else s.ljust(width)

    def hdr():
        h = (f"  │ {cell('App',W['app'])} │ {cell('Compiler',W['compiler'])} │"
             f" {cell('Job Type',W['job_type'])} │ {cell('Iter',W['iter'])} │"
             f" {cell('Threads',W['threads'])} │ {cell('NP',W['np'])} │"
             f" {cell('Status',W['status'])}")
        if show_gflops:
            h += f" │ {cell('Gflops',W['gflops'],True)} │ {cell('Avg Gflops',W['avg_gflops'],True)}"
        if show_triad:
            h += f" │ {cell('Triad MB/s',W['triad'],True)} │ {cell('Avg Triad',W['avg_triad'],True)}"
        h += f" │ {cell('Log Dir',W['log'])} │"
        return h

    def data_row(r):
        ok        = r["status"] == "PASS"
        sym       = "✔" if ok else "✗"
        s         = f"{sym} {r['status']}"
        short_log = os.path.basename(r.get("log_dir", "-")) if r.get("log_dir") else "-"

        row = (f"  │ {cell(r['app'],W['app'])} │ {cell(r['compiler'],W['compiler'])} │"
               f" {cell(r['job_type'],W['job_type'])} │ {cell(r.get('iteration','-'),W['iter'])} │"
               f" {cell(r.get('threads','-'),W['threads'])} │ {cell(r.get('np','-'),W['np'])} │"
               f" {cell(s,W['status'])}")

        if show_gflops:
            if r["app"] in ("hpl", "hpcg") and r.get("job_type") == "run":
                gf     = f"{r['gflops']:.4e}" if r.get("gflops") is not None else "-"
                avg_gf = f"{avg_map[r['app']]:.4e}" if r["app"] in avg_map else "-"
            else:
                gf = avg_gf = "-"
            row += f" │ {cell(gf,W['gflops'],True)} │ {cell(avg_gf,W['avg_gflops'],True)}"

        if show_triad:
            if r["app"] == "stream" and r.get("job_type") == "run":
                tr     = f"{r['triad']:.2f}" if r.get("triad") is not None else "-"
                avg_tr = f"{avg_map['stream']:.2f}" if "stream" in avg_map else "-"
            else:
                tr = avg_tr = "-"
            row += f" │ {cell(tr,W['triad'],True)} │ {cell(avg_tr,W['avg_triad'],True)}"

        row += f" │ {cell(short_log,W['log'])} │"
        return row

    w = sum(W.values()) + 3 * len(W) + 1
    border_top = "  ┌" + "─" * (w - 4) + "┐"
    border_mid = "  ├" + "─" * (w - 4) + "┤"
    border_bot = "  └" + "─" * (w - 4) + "┘"

    print()
    print("  ╔══════════════════════════════════════╗")
    print("  ║   CARIBOU  —  POST-PROCESSING REPORT ║")
    print("  ╚══════════════════════════════════════╝")
    print()
    print(border_top)
    print(hdr())
    print(border_mid)

    pass_count = fail_count = 0
    for r in results:
        print(data_row(r))
        if r["status"] == "PASS":
            pass_count += 1
        else:
            fail_count += 1

    print(border_bot)
    print()
    total = pass_count + fail_count
    print(f"  Summary: {total} jobs  │  ✔ PASS: {pass_count}  │  ✗ FAIL: {fail_count}")
    if "hpl"    in avg_map:
        print(f"  Avg Gflops (HPL)   : {avg_map['hpl']:.4e}  (over {len(buckets['hpl'])} run(s))")
    if "hpcg"   in avg_map:
        print(f"  Avg Gflops (HPCG)  : {avg_map['hpcg']:.4e}  (over {len(buckets['hpcg'])} run(s))")
    if "stream" in avg_map:
        print(f"  Avg Triad MB/s     : {avg_map['stream']:.2f}  (over {len(buckets['stream'])} run(s))")

    failures = [r for r in results if r["status"] == "FAIL"]
    if failures:
        print()
        print("  ✗ FAILED JOBS:")
        for r in failures:
            print(f"    • {r['app']} / {r['job_type']}"
                  f"  iter={r.get('iteration', '-')}"
                  f"  threads={r.get('threads', '-')}"
                  f"  np={r.get('np', '-')}"
                  f"  jobid={r.get('job_id', '-')}")
            if r.get("log_dir"):
                print(f"      Log dir : {r['log_dir']}")
    print()


# ─────────────────────────────────────────────────────────────
# PIPELINE RUNNER  (single case)
# ─────────────────────────────────────────────────────────────

def run_one_case(app, threads, np, iteration, action, workspace,
                 compiler_name, compiler_info, system_info,
                 profiling=False, metrics=None, profile_duration=10):
    results   = []
    build_dir = os.path.join(workspace, app, "build")
    run_dir   = os.path.join(workspace, app, "run",
                             f"iter{iteration}_t{threads}_np{np}")
    os.makedirs(build_dir, exist_ok=True)
    os.makedirs(run_dir,   exist_ok=True)

    system_info["compiler_name"] = compiler_name

    build_jid = None
    binary    = None

    # ── BUILD ──────────────────────────────────────────────
    if action in ("build", "all"):

        temp_b_out = os.path.join(build_dir, f"{app}.out")
        temp_b_err = os.path.join(build_dir, f"{app}.err")

        if app == "stream":
            build_jid = stream_app.build(
                build_dir, threads, compiler_info, system_info,
                out_log=temp_b_out, err_log=temp_b_err,
                workspace=workspace)
        elif app == "hpl":
            build_jid, binary = hpl_app.build(
                build_dir, threads, compiler_info, compiler_name,
                out_log=temp_b_out, err_log=temp_b_err,
                workspace=workspace)
        elif app == "hpcg":                                         # ← CHANGE 2
            build_jid, binary = hpcg_app.build(
                build_dir, threads, compiler_info, compiler_name,
                out_log=temp_b_out, err_log=temp_b_err,
                workspace=workspace)

        log_dir, b_out, b_err, b_sbatch, b_case = make_job_logdir(
            workspace, app, job_type="build")

        if build_jid and build_jid not in ("skip", "bash"):
            wait_and_show(build_jid, temp_b_out, f"build_{app}")

        for src, dst in [(temp_b_out, b_out), (temp_b_err, b_err)]:
            if os.path.exists(src):
                shutil.move(src, dst)

        write_case_setup(b_case, app, "build", compiler_name, compiler_info,
                         threads, np, iteration, system_info)

        sbatch_src = os.path.join(build_dir,
            f"build_hpl_{compiler_name}.sh"  if app == "hpl"  else
            f"build_hpcg_{compiler_name}.sh" if app == "hpcg" else
            "build_stream.sh")
        if os.path.exists(sbatch_src):
            shutil.copy(sbatch_src, b_sbatch)

        print(f"  ✔  BUILD  →  {log_dir}")

        b_ok = job_succeeded(build_jid, b_out, app=app, job_type="build")

        if build_jid not in ("skip", "bash", None):
            results.append({
                "app":       app,
                "compiler":  compiler_name,
                "job_type":  "build",
                "iteration": iteration,
                "threads":   threads,
                "np":        np,
                "status":    "PASS" if b_ok else "FAIL",
                "log_dir":   log_dir,
                "job_id":    build_jid,
                "gflops":    None,
                "triad":     None,
            })

        if not b_ok:
            print(f"\n  ✗  Build failed — skipping run for"
                  f" iter={iteration} threads={threads} np={np}")
            return results

    # ── RUN ────────────────────────────────────────────────
    if action in ("run", "all"):

        temp_out = os.path.join(run_dir, f"{app}.out")
        temp_err = os.path.join(run_dir, f"{app}.err")

        if binary is None and app == "hpl":
            binary = os.path.join(
                build_dir, "hpl-2.3", "bin",
                f"Linux_HPL_{compiler_name}", "xhpl")
        if binary is None and app == "hpcg":                        # ← CHANGE 3
            binary = os.path.join(build_dir, "xhpcg")

        # ── PROFILING MODE: direct mpirun, uProf profiles system-wide ──
        if profiling and app == "hpl":

            direct_np = np

            proc, direct_out, out_f, err_f = hpl_app.run_direct(
                build_dir, run_dir, direct_np, threads, binary,
                compiler_info, system_info,
                out_log=temp_out, err_log=temp_err)

            WARMUP_SECS = 5
            print(f"  Waiting {WARMUP_SECS}s for HPL to warm up ...")
            time.sleep(WARMUP_SECS)

            uprof.run_uprof(
                benchmark = app.upper(),
                metrics   = metrics or uprof.DEFAULT_METRICS,
                duration  = profile_duration,
            )

            print("  Waiting for HPL to finish ...")
            proc.wait()
            out_f.close()
            err_f.close()
            print("  ✔  HPL finished.")

            run_jid = f"direct_{iteration}_t{threads}_np{direct_np}"
            r_out = temp_out
            r_err = temp_err
            if os.path.getsize(r_out) == 0:
                for candidate in [
                    os.path.join(run_dir, "hpl.out"),
                    os.path.join(os.path.dirname(run_dir), "hpl.out"),
                ]:
                    if candidate != r_out and os.path.exists(candidate) \
                            and os.path.getsize(candidate) > 0:
                        shutil.copy(candidate, r_out)
                        print(f"  [debug] Copied HPL output from {candidate}")
                        break

        # ── NORMAL MODE: SLURM ─────────────────────────────────────────
        else:
            if app == "stream":
                run_jid, _ = stream_app.run(
                    build_dir, run_dir, threads, build_jid, compiler_info,
                    out_log=temp_out, err_log=temp_err,
                    workspace=workspace)
            elif app == "hpl":
                run_jid, _ = hpl_app.run(
                    build_dir, run_dir, np, threads, build_jid,
                    binary, compiler_info, system_info,
                    out_log=temp_out, err_log=temp_err,
                    workspace=workspace)
            elif app == "hpcg":                                     # ← CHANGE 4
                run_jid, _ = hpcg_app.run(
                    build_dir, run_dir, np, threads, build_jid,
                    binary, compiler_info, system_info,
                    out_log=temp_out, err_log=temp_err,
                    workspace=workspace)

            if run_jid and run_jid not in ("bash",):
                wait_and_show(run_jid, None, f"run_{app}")

            r_out = temp_out
            r_err = temp_err

        # ── LOG HANDLING (common to both paths) ────────────────────────
        log_dir, final_out, final_err, r_sbatch, r_case = make_job_logdir(
            workspace, app, job_type="run")

        for src, dst in [(r_out, final_out), (r_err, final_err)]:
            if os.path.exists(src):
                shutil.move(src, dst)

        write_case_setup(r_case, app, "run", compiler_name, compiler_info,
                         threads, np, iteration, system_info)

        sbatch_src = os.path.join(run_dir, f"run_{app}.sh")
        if os.path.exists(sbatch_src):
            shutil.copy(sbatch_src, r_sbatch)

        if app == "stream":
            print_stream_results(final_out)

        r_ok   = job_succeeded(run_jid, final_out, app=app, job_type="run")
        gflops = (extract_gflops(final_out)      if app == "hpl"    else
                  extract_gflops_hpcg(final_out) if app == "hpcg"   else None)
        triad  = extract_triad(final_out)        if app == "stream" else None

        print(f"  ✔  RUN    →  {log_dir}")

        results.append({
            "app":       app,
            "compiler":  compiler_name,
            "job_type":  "run",
            "iteration": iteration,
            "threads":   threads,
            "np":        np,
            "status":    "PASS" if r_ok else "FAIL",
            "log_dir":   log_dir,
            "job_id":    run_jid,
            "gflops":    gflops,
            "triad":     triad,
        })

    return results


# ─────────────────────────────────────────────────────────────
# MAIN PIPELINE  (sweeps iterations × threads × np)
# ─────────────────────────────────────────────────────────────

def run_pipeline(app, threads_list, np_list, iterations_list, action, workspace,
                 compiler_name, compiler_info,
                 profiling=False, metrics=None, profile_duration=10):
    system_info = get_system_info()
    all_results = []

    write_lmod_module(app, compiler_name, compiler_info, workspace)

    for iteration in iterations_list:
        for threads in threads_list:
            for np in np_list:
                case_results = run_one_case(
                    app, threads, np, iteration, action, workspace,
                    compiler_name, compiler_info, dict(system_info),
                    profiling=profiling,
                    metrics=metrics,
                    profile_duration=profile_duration,
                )
                all_results.extend(case_results)

    print_summary_table(all_results)

    summary_path = os.path.join(workspace, app, "logs", "summary.json")
    os.makedirs(os.path.dirname(summary_path), exist_ok=True)
    with open(summary_path, "w") as f:
        json.dump(all_results, f, indent=2)
    print(f"  Summary JSON : {summary_path}")

    return all_results


# ─────────────────────────────────────────────────────────────
# SLURM PREPROCESSING — standalone mode
# ─────────────────────────────────────────────────────────────

def run_slurm_preprocessing():
    info = get_system_info()
    print("=" * 64)
    print("     Mini Caribou  —  SLURM Preprocessing Check")
    print("=" * 64)
    print(f"  Host   : {info['host']}")
    print(f"  Cores  : {info['cores']}")
    print(f"  RAM    : {info['mem_mb']} MB total  /  {info['avail_mb']} MB avail")
    print("=" * 64)
    preprocess_slurm()


# ─────────────────────────────────────────────────────────────
# ARG PARSE
# ─────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description="Mini Caribou — WSL HPC Benchmark Manager",
        formatter_class=argparse.RawTextHelpFormatter)

    p.add_argument("--slurm",
        choices=["preprocessing"],
        metavar="MODE",
        help=(
            "SLURM operation to run standalone.\n"
            "  preprocessing  — check tools, start munge/daemons, verify sinfo"
        ))

    p.add_argument("--apps",
        choices=["stream", "hpl", "hpcg"],       # ← CHANGE 5: hpcg added
        help="Benchmark app to run")
    p.add_argument("--action",
        choices=["build", "run", "all"], default="all",
        help="Pipeline stage (default: all)")
    p.add_argument("--threads",
        type=int, nargs="+", default=[1], metavar="T",
        help="OMP thread counts to sweep. e.g. --threads 1 2 4\nDefault: 1")
    p.add_argument("--np",
        type=int, nargs="+", default=None, metavar="N",
        help="MPI rank counts to sweep. e.g. --np 1 2 4\nDefault: system core count")
    p.add_argument("--iterations",
        type=int, nargs="+", default=[1], metavar="N",
        help="--iterations 3 → runs iter 1,2,3\nDefault: 1")
    p.add_argument("--compiler",
        choices=["gcc", "aocc", "icc"], default=None,
        help="Force specific compiler (default: auto-detect)")
    p.add_argument("--skip-preprocess",
        action="store_true",
        help="Skip compiler and SLURM preprocessing")

    # uProf profiling args
    uprof.add_uprof_args(p)

    return p.parse_args()


# ─────────────────────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────────────────────

def main():
    args = parse_args()

    if args.slurm == "preprocessing":
        run_slurm_preprocessing()
        return

    if not args.apps:
        print("  ✗  Either --slurm <mode> or --apps <app> is required.")
        print("      python3 caribou.py --slurm preprocessing")
        print("      python3 caribou.py --apps stream --action all")
        sys.exit(1)

    workspace = os.path.join(BASE_DIR, "workspace")

    nproc        = int(subprocess.run(
        ["nproc"], capture_output=True, text=True).stdout.strip())
    threads_list = args.threads
    np_list      = args.np if args.np else [nproc]

    raw_iters  = args.iterations
    iters_list = list(range(1, raw_iters[0] + 1)) if len(raw_iters) == 1 else raw_iters

    print("=" * 64)
    print("     Mini Caribou  —  WSL HPC Benchmark Manager")
    print("=" * 64)
    print(f"  App        : {args.apps.upper()}")
    print(f"  Action     : {args.action}")
    print(f"  Threads    : {threads_list}")
    print(f"  NP         : {np_list}")
    print(f"  Iterations : {iters_list}")
    print(f"  Profiling  : {'ON — ' + ', '.join(args.metrics) if args.profiling else 'OFF (SLURM)'}")
    print(f"  Workspace  : {workspace}")
    print("=" * 64)

    if args.profiling:
        uprof.check_uprof()

    if args.compiler:
        compiler_name = args.compiler
        compiler_info = COMPILERS[args.compiler]
        if not args.skip_preprocess:
            preprocess_compiler_forced(compiler_name, compiler_info)
        print(f"  ✔  Compiler : {compiler_name.upper()}  ({compiler_info['cc']})")
    else:
        if not args.skip_preprocess:
            compiler_name, compiler_info = preprocess_compiler()
        else:
            compiler_name, compiler_info = detect_compiler()
            print(f"  ✔  Compiler : {compiler_name.upper()}  ({compiler_info['cc']})")

    os.makedirs(workspace, exist_ok=True)

    run_pipeline(
        app=args.apps,
        threads_list=threads_list,
        np_list=np_list,
        iterations_list=iters_list,
        action=args.action,
        workspace=workspace,
        compiler_name=compiler_name,
        compiler_info=compiler_info,
        profiling=args.profiling,
        metrics=args.metrics,
        profile_duration=args.profile_duration,
    )


if __name__ == "__main__":
    main()
